### ISSUE TITLE
The task tracker has an actual completion date, but ANET does not

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#1033]
The task SME cannot update the actual completion date for tasks.  Over two hundred tasks have been completed.  The only way to update the actual completion date is to use a query.

The tasks table has two date fields:
projectedCompletion
plannedCompletion

The projectedCompletion date field is being used in ANET, i.e. administrators can add values to this date field and edit this date field.

The plannedCompletion date field is not being used at all.  The only value is NULL.  Is this date field going to be used as the actual completion date field?

**Comment by VassilIordanov** [comment]
anet.yml defines which database fields are visible to the user interface.
If you have anet.yml with something like:
```
      projectedCompletion:
        label: Projected Completion
        placeholder: 'Fill in the projected completion date'
      plannedCompletion:
        label: 'Planned Completion'
        placeholder: 'Fill in the planned completion date'
```
then both will be visible. I will update the production anet.yml tomorrow
