### ISSUE TITLE
Add all field definitions to anet.yml

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#1287]
Make sure all fields are defined in anet.yml

i.e.
```
    report:
      intent: Meeting goal (purpose)
```
should be:

```
    report:
      intent:
        label:  Meeting goal (purpose)
        placeholder: What is the engagement supposed to achieve
```
