### ISSUE TITLE
Add ANET instance specific fields to reports and people

### ISSUE THREAD

**Issue by maradragan** [NCI-Agency/anet#2352]
For different ANET instances we would like to have a different set of extra fields to be added to reports and people.

First implementation step
- [x] make an example schema definition for extra fields
- [x] make sure the simple fields are added to the form (based on the schema definition)
- [x] make sure the fields can de filled
- [x] make sure the fields can be validated
- [x] save the content of the extra fields in the db
- [x] make sure they are displayed on the show page after being saved
- [x] make sure the saved values are displayed on the edit form

Types of fields:
- [x]  text
- [x]  number
- [x]  date
- [x]  datetime
- [x]  enum => radio buttons, save one value
- [x]  enumset => checkbox buttons, save an array of values
- [x]  array_of_objects => like the approval steps of an organisation
- [x]  special_field => allows us to specify a widget for it

Maybe later
- [x] It can be that the extra fields also depend on the context (like whether it is available for a past 
or upcoming engagement) => make it possible to specify in the configuration the context for the field to be visible
- [x] make it possible to set the renderer to be used for a field
- [x] add Likert scale renderer

Maybe even later:
- [x] Do not validate fields which are invisible
- [ ] Make it be possible to search on these extra fields?
- [ ] Make it be possible to reset the enum field?
- [ ] Make this also possible for the other object types (one json field per object type)
- [ ] More complex fields 

Will NOT DO:
- make it possible to manage the definitions of the extra fields through the admin interface => not needed, it is enough if they can be edited via anet.yml
- do we want these extra fields in the full text search? How would a json field in combination with full-text search work? => no, we will not add them to the full-text search

**Comment by VassilIordanov** [comment]
>>  some examples, in order to know how to structure the schema

I suggest to make a list of fields

```
    report:
      intent: Meeting goal (purpose)
      atmosphere: Atmospherics
      atmosphereDetails: Atmospherics details
      cancelled: ''
      reportTags: Tags
      nextSteps: Next steps
      keyOutcomes: Key outcomes
      reportText: Engagement details
			customContent:
        justification:
          type: text
          visible: $.position.[?(@.identificationCode && /^(Z|z)/.test(@.identificationCode))]
          label: Effort number
          placeholder: Placeholder text
	        style:
  	        height: 400px
        nlt:
          type: date
          visible: $.position.[?(@.identificationCode && /^(Z|z)/.test(@.identificationCode))]
          label: Not later than
        nlt:
          type: enum
					enumValues: ["red","green","blue"]
          visible: $.position.[?(@.identificationCode && /^(Z|z)/.test(@.identificationCode))]
          label: Not later than
```

with each field having a:
- property name (i.e. `justification`), to be used as json property value
- type, we can start with the following types:
  - text
  - number
  - enum
- later we could add types that are references to one (or more) ANET objects:
  - Person
  - Report
  - Organization
  - Position
  - Location
- a style (to be able to override the style, just like `longName` for example
- a `visible` expression, that is a function (maybe jsonpath-plus or something similar) that looks at some context variables, such as the author or where in the approval chain the report stands.
- a label and placeholder, just like other items
- possibly in the future some validation logic?

>> make it possible to manage the definitions of the extra fields through the admin interface
I don't think that editing through the admin inteface is needed. editing through `anet.yml` would be enough

>> should it be possible to search on these extra fields?

yes, using the MSSQL/Postgres SQL json extensions, 


>> do we want these extra fields in the full text search? How would a json field in combination with full-text search work?

I do not think we should be thinking of fts at this moment. I think a custom search on that field will be more useful
