### ISSUE TITLE
Add MGRS coordinate format

### ISSUE THREAD

**Issue by ysf-simsoft** [NCI-Agency/anet#3042]
Define in dictionary a geo location format.
At first, the two possible choices are lat/lon and [MGRS](https://en.wikipedia.org/wiki/Military_Grid_Reference_System).
Display location throughout the UI in the specified format.

We created a geo location field widget as part of #2984. It should be improved to support multiple formats:

- lon,lat
- MGRS (see https://github.com/proj4js/mgrs)

anet.yml should specify which format should be used:
```
dictionary:
  SUPPORT_EMAIL_ADDR: support@example.com
  fields:
    location:
      format: MGRS
```
Part of epic [#547](https://github.com/NCI-Agency/anet/issues/244)
