### ISSUE TITLE
Add anet objects to custom fields type

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#3143]
Users would like to have custom fields that reference other ANET objects. It is suggested to add 2 new custom fields:
- ANET object
- An array of ANET objects
Both could bring the auto-suggest dialogs to choose the objects. The custom field definition will probably also require specifying the types of ANET objects.

Example:
```
     customFields:
        testANETreferenceField:
          type: array_of_anet_objects
          anetObjectTypes: [Person,Position,Organization]
          label: Testing ANET references
 
```
