### ISSUE TITLE
No color styling when displaying enum values

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#3799]
**Describe the bug**
The read only view of enums does not contain colors

**To Reproduce**
1. Create a custom field with for a person of type _enum_ with choices containing colors, like:
```yml
            test:
              type: enum
              label: Project status
              choices:
                GREEN:
                  label: Green
                  color: '#c2ffb3'
                AMBER:
                  label: Amber
                  color: '#ffe396'
```
2. The person editor displays the colors
3. When viewing the person, the colors are not there

**Expected behavior**
`ReadonlyEnumField` should carry over colors like `EnumField` does

Other issue related to choice: #3804
