### ISSUE TITLE
Label of "Yes" and "No" choice not visible.

### ISSUE THREAD

**Issue by midmarch** [NCI-Agency/anet#3865]
If the `label` of an option in assesments `choice` is either `No` or `Yes`:

```yml
assessments:
  - recurrence: once
    relatedObjectType: report
    questions:
      haveBreakfast:
        label: "Ring my bell?"
        type: enum
        choices:
          yes:
            label: Yes
          no:
            label: No        
```
