### ISSUE TITLE
Change title on permissions button for advisor positions

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#519]
When creating a new advisor position, the "Type" options are "Advisor Billet" and "Principal Position" (or words to that effect).

But the "Permissions" section also uses "Advisor Billet" as a type of permission.  In actuality, it is called "ANET User" permissions here.

**Comment by VassilIordanov** [comment]
Brad, this is configurable in the anet.yml. I suggest changing 
```    advisor:
      person:
        name: NATO Member
        countries:
....
      position:
        name: Advisor Billet
```
to
```    advisor:
      person:
        name: NATO Member
        countries:
....
      position:
        name: Advisor
```

**Comment by dspCarlson** [comment]
@VassilIordanov

In the YML file, advisor position type label is being used as a user permission type.
Advisor Position Type <> Permission Type, i.e. "NATO Billet" <> "ANET User"

 Is there a way to distinguish between the type of position (NATO Billet vs. principal position) and type of permission (ANET User, ANET Super User, ANET Administrator)?

**Comment by dspCarlson** [comment]
@VassilIordanov ANET is using two descriptions to distinguish between three types:

Position Type
Person Type
Permissions Type

For the permissions type it would be nice if the wording was consistent with the other two permissions, i.e. ANET User, ANET Super User and ANET Administrator.  Right now, "ANET User" is "Advisor Billet."

This is not a high priority.  Just trying to make the wording consistent for an easier understanding.

**Comment by gjvoosten** [comment]
@dspCarlson Nicest way to solve this is to add an extra setting `type` to the `anet.yml` for each position like so:
```
    advisor:
      position:
        name: NATO Billet
        type: ANET User
    principal:
      position:
        name: Afghan Tashkil
        type: Afghan Partner
    superUser:
      position:
        type: ANET Super User
    administrator:
      position:
        type: ANET Administrator
```
So we add `advisor.position.type` and `principal.position.type` (although the latter is not used visibly in the UI), and change `superUser.position.name` ⇒ `superUser.position.type` and `administrator.position.name` ⇒ `administrator.position.type`.
Would that address your request?
