### ISSUE TITLE
Define what kind of statistical properties we want recreated in test data

### ISSUE THREAD

**Issue by VassilIordanov** [NCI-Agency/anet#53]
As a potential input to the simulator, I would like to consider the dataset properties:

I suggest the following format for specifying the dataset properties (obviously to be refined):

```yaml
advisorOrgs:
  rootNumber: 5
  depth:
    distribution: gaussian
    mean: 6
    stdDeviation: 1
  positions:
    number:
      distribution: gaussian
      mean: 15
      stdDeviation: 1
    filled: .7
    admin: .01
    superUsers: .2
principalOrgs:
  rootNumber: 5
  depth:
    distribution: gaussian
    mean: 7
    stdDeviation: 1
  positions:
    number:
      distribution: gaussian
      mean: 15
      stdDeviation: 1
    filled: .7
engagementChannels:
  number: 200
  deviationFromParent: .5
reports:
  number: 50000
  principalAttendance:
    distribution: gaussian
    mean: 5
    stdDeviation: 2
  advisorAttendance:
    distribution: gaussian
    mean: 2
    stdDeviation: 1
```
