### ISSUE TITLE
Automatically deactivate users when end of tour occurs

### ISSUE THREAD

**Issue by dspCarlson** [NCI-Agency/anet#530]
Reproduced the following in the staging environment:

As an administrator, I can set anybody else's profile "Status" to "Inactive" using the buttons, but I cannot set my own profile to "Inactive."

As a super user, I can set other user's profile "Status" to "Inactive" using the buttons if the users are assigned to my organization, but I cannot set my own profile to "Inactive."

As a user, I cannot set my user profile "Status" to "Inactive" using the buttons.

**Comment by VassilIordanov** [comment]
After speaking with @dspCarlson , we think the correct behavior should be:

- Once a user's end of tour date becomes current, automatically set their person to inactive and remove that person from the occupied position
- send users 3 emails - 15, 30 and 45 days prior to their end of tour, asking them to edit their end of tour date in ANET in case it is not correct.

Then, there is no need for any user to manually deactivate themselves

**Comment by VassilIordanov** [comment]
Just an idea (feel free to correct/improve....). It would be nice if define in anet.yml:

```
dictionary:
  automaticallyInactivateUsers:
    emailReminders:
      - daysPrior: 15
      - daysPrior: 30
      - daysPrior: 45
    clearDomainUserName:
      - test: 'some regex or other test for domain name'
```


So, we can have the following behavior:
- if automaticallyInactivateUsers is not defined - do not auto inactivate
- we can list as many email reminders with different time parameters (or other parameters if needed)
- we can list patterns for which domain names should be cleared. if domain name matches pattern - clear the domain name
